openapi: 3.0.0
info:
  title: Messages API
  version: 1.0.0
paths:
  /messages:
    get:
      summary: Get Messages
      description: Retrieves a list of messages.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  messages:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        text:
                          type: "string"
                        status:
                          type: "string"
                          enum:
                            - "sent"
              example:
                messages:
                  - text: "Hello, World!"
                    status: "sent"
                  - text: "How are you today?"
                    status: "sent"
                  - text: "Thanks, I'm fine. How about you?"
                    status: "sent"
  /messages/send:
    get:
      summary: Send a Message
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                text:
                  type: "string"
      responses:
        '204':
          description: Successfully sent
